image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  IMAGE_TAG: $CI_COMMIT_REF_NAME
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - security
  - deploy
  - notify

# ---------------- BUILD ----------------
build_backend:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$IMAGE_TAG backend/
    - docker push $CI_REGISTRY_IMAGE/backend:$IMAGE_TAG

build_frontend:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG frontend/
    - docker push $CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG

# ---------------- TEST ----------------
test_backend:
  stage: test
  image: node:20
  cache:
    key: backend-deps
    paths:
      - backend/node_modules/
  script:
    - cd backend
    - npm install
    - npm test

test_frontend:
  stage: test
  image: node:20
  cache:
    key: frontend-deps
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm install
    - npm run lint
    - npm test

# ---------------- SECURITY ----------------
dependency_scan:
  stage: security
  image: node:20
  cache:
    key: backend-deps
    policy: pull
  script:
    - cd backend
    - npm audit --audit-level=high || true

container_scan:
  stage: security
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  variables:
    TRIVY_USERNAME: $CI_REGISTRY_USER
    TRIVY_PASSWORD: $CI_REGISTRY_PASSWORD
    TRIVY_AUTH_URL: $CI_REGISTRY
  script:
    - trivy image $CI_REGISTRY_IMAGE/backend:$IMAGE_TAG

# ---------------- DEPLOY ----------------
deploy_backend:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Updating backend image tag in manifest"
    - IMAGE="$CI_REGISTRY_IMAGE/backend:$IMAGE_TAG"
    - sed -i "s|image:.*backend.*|image: $IMAGE|" backend-deployment.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "preprod" || $CI_COMMIT_BRANCH == "prod"'
      changes:
        - backend/**/*
        - backend-deployment.yaml

deploy_frontend:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Updating frontend image tag in manifest"
    - IMAGE="$CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG"
    - sed -i "s|image:.*frontend.*|image: $IMAGE|" frontend-deployment.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "preprod" || $CI_COMMIT_BRANCH == "prod"'
      changes:
        - frontend/**/*
        - frontend-deployment.yaml

# ---------------- NOTIFY ----------------
notify:
  stage: notify
  image: alpine:latest
  script:
    - echo "Deployment triggered. ArgoCD will sync automatically."