stages:
  - build

image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  # Using the branch name (dev, preprod, prod) as the docker tag
  IMAGE_TAG: $CI_COMMIT_REF_NAME
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build_and_push_backend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME backend/
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "preprod" || $CI_COMMIT_BRANCH == "prod"
      changes:
        - backend/**/*
        - backend-deployment.yaml

build_and_push_frontend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME frontend/
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "preprod" || $CI_COMMIT_BRANCH == "prod"
      changes:
        - frontend/**/*
        - frontend-deployment.yaml