apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: harshasha/harsha-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
