apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.gitlab.com/harshavardhan81860/harsha/backend:dev
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: gitlab-registry-secret